name: NCCT_PE
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=2.0.5=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - ca-certificates=2025.2.25=h06a4308_0
  - comm=0.2.1=py38h06a4308_0
  - debugpy=1.6.7=py38h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - executing=0.8.3=pyhd3eb1b0_0
  - importlib_metadata=7.0.1=hd3eb1b0_0
  - ipykernel=6.29.5=py38h06a4308_0
  - ipython=8.12.2=py38h06a4308_0
  - jedi=0.19.1=py38h06a4308_0
  - jupyter_client=8.6.0=py38h06a4308_0
  - jupyter_core=5.7.2=py38h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - matplotlib-inline=0.1.6=py38h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=py38h06a4308_0
  - openssl=3.0.16=h5eee18b_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=24.2=py38h06a4308_0
  - prompt-toolkit=3.0.43=py38h06a4308_0
  - psutil=5.9.0=py38h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pygments=2.15.1=py38h06a4308_1
  - python=3.8.20=he870216_0
  - python-dateutil=2.9.0post0=py38h06a4308_2
  - pyzmq=25.1.2=py38h6a678d5_0
  - readline=8.2=h5eee18b_0
  - setuptools=75.1.0=py38h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tk=8.6.14=h39e8969_0
  - tornado=6.4.1=py38h5eee18b_0
  - traitlets=5.14.3=py38h06a4308_0
  - typing_extensions=4.11.0=py38h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.44.0=py38h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zeromq=4.3.5=h6a678d5_0
  - zipp=3.20.2=py38h06a4308_0
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.2.1
      - adamp==0.3.0
      - antlr4-python3-runtime==4.9.3
      - argparse==1.4.0
      - batchgenerators==0.25.1
      - black==24.8.0
      - cachetools==5.5.2
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - click==8.1.8
      - cloudpickle==3.1.1
      - contextlib2==21.6.0
      - contourpy==1.1.1
      - cycler==0.12.1
      - cython==3.0.12
      - deprecated==1.2.18
      - detectron2==0.6
      - dicom2nifti==2.6.0
      - efficientnet-pytorch==0.7.1
      - einops==0.8.1
      - filelock==3.16.1
      - fonttools==4.56.0
      - fsspec==2025.3.0
      - future==1.0.0
      - fvcore==0.1.5.post20221221
      - gco-wrapper==3.0.9
      - google-auth==2.38.0
      - google-auth-oauthlib==1.0.0
      - grpcio==1.70.0
      - h5py==3.11.0
      - huggingface-hub==0.30.1
      - humanize==4.10.0
      - hydra-core==1.3.2
      - idna==3.10
      - imageio==2.35.1
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - iopath==0.1.9
      - ipdb==0.13.13
      - jinja2==3.1.6
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - linecache2==1.0.0
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - mat73==0.65
      - matplotlib==3.7.5
      - mdurl==0.1.2
      - medpy==0.5.2
      - ml-collections==0.1.1
      - monai==1.3.2
      - mpmath==1.3.0
      - munch==4.0.0
      - mypy-extensions==1.0.0
      - narwhals==1.42.1
      - networkx==3.1
      - nibabel==5.2.1
      - nnunet==1.7.1
      - numpy==1.24.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - packaging==24.2
      - pandas==2.0.3
      - pathspec==0.12.1
      - pillow==10.4.0
      - piq==0.8.0
      - platformdirs==4.3.6
      - plotly==6.5.2
      - portalocker==3.0.0
      - pretrainedmodels==0.7.4
      - protobuf==5.29.4
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycocotools==2.0.7
      - pydicom==2.4.4
      - pyparsing==3.1.4
      - python-gdcm==3.0.24.1
      - pytorch-msssim==1.0.0
      - pytz==2025.2
      - pywavelets==1.4.1
      - pyyaml==6.0.2
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - rich==14.0.0
      - rsa==4.9
      - safetensors==0.5.3
      - scikit-image==0.21.0
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - segmentation-models-pytorch==0.3.3
      - shellingham==1.5.4
      - simpleitk==2.4.1
      - six==1.17.0
      - ssim==0.3.0
      - sympy==1.13.3
      - tabulate==0.9.0
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - termcolor==2.4.0
      - threadpoolctl==3.5.0
      - tifffile==2023.7.10
      - timm==0.9.2
      - tomli==2.2.1
      - torch==2.4.1
      - torchio==0.20.1
      - torchvision==0.19.1
      - tqdm==4.67.1
      - traceback2==1.4.0
      - triton==3.0.0
      - typer==0.15.2
      - typing-extensions==4.13.0
      - tzdata==2025.2
      - unittest2==1.1.0
      - urllib3==2.2.3
      - werkzeug==3.0.6
      - wrapt==1.17.2
      - yacs==0.1.8
prefix: /opt/miniconda3/envs/HT-nnunet
